version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "dillon-barendt"
    assignees:
      - "dillon-barendt"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group related updates together
    groups:
      pytest:
        patterns:
          - "pytest*"
      pydantic:
        patterns:
          - "pydantic*"
      dev-tools:
        patterns:
          - "ruff"
          - "mypy"
          - "black"
          - "pre-commit"
          - "hypothesis"
    # Ignore specific dependencies if needed
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
    # Auto-merge minor and patch updates for dev dependencies
    auto-merge:
      - match:
          dependency-type: "development"
          update-type: "semver:patch"
      - match:
          dependency-type: "development"
          update-type: "semver:minor"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "dillon-barendt"
    assignees:
      - "dillon-barendt"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    # Group GitHub Actions updates
    groups:
      actions:
        patterns:
          - "*"
