site_name: duratypes Documentation
site_description: Typed duration utilities for Python and Pydantic
site_author: Dillon Barendt
site_url: https://dillon-barendt.github.io/duratypes

repo_name: dillon-barendt/duratypes
repo_url: https://github.com/dillon-barendt/duratypes
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - User Guide:
    - Basic Usage: usage.md
    - Pydantic Integration: pydantic.md
    - Error Handling: errors.md
    - Performance: performance.md
  - API Reference:
    - Core Functions: api/core.md
    - Types: api/types.md
    - Exceptions: api/exceptions.md
  - Advanced:
    - Migration Guide: migration.md
    - FAQ: faq.md
    - Contributing: contributing.md
  - Changelog: changelog.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dillon-barendt/duratypes
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/duratypes/
