name: Feature Request
description: Suggest a new feature or enhancement for duratypes
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        I'm always frustrated when...
        This would help with...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        I would like to see...
        The feature should work like...
        It could be implemented by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: |
        Alternative approaches could be...
        I also considered...
        Another way to solve this would be...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Provide examples of how you envision the feature being used.
      render: python
      placeholder: |
        from duratypes import parse_duration

        # Example of how the new feature would be used
        result = parse_duration("1 hour and 30 minutes")  # New fuzzy parsing
        print(result)  # 5400
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple addition or modification
        - Medium - Moderate changes required
        - High - Significant changes or new functionality
        - Unknown - Not sure about implementation complexity
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: |
        Consider the impact this feature might have:
        - Would it be a breaking change?
        - Would it affect performance?
        - Would it require new dependencies?
      placeholder: |
        This feature would...
        It might affect...
        Considerations include...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, links to similar features in other libraries,
        or anything else that would help us understand your request.
      placeholder: |
        Related links...
        Similar features in other libraries...
        Additional considerations...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have considered how this feature fits with the project's goals and scope
          required: true
        - label: I would be willing to help implement this feature (if I have the skills)
          required: false
