name: Build & Publish to TestPyPI and PyPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-distribution:
    name: Build Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tools
        run: python -m pip install --upgrade build twine
      - name: Build package
        run: python -m build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: &dist_name dist
          path: &dist_path dist/

  publish-testpypi:
    name: Publish to TestPyPI
    needs: build-distribution
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: *dist_name
          path: *dist_path
      - name: Install & Upgrade Twine
        run: python -m pip install --upgrade twine
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  publish-pypi:
    name: Publish to PyPI
    needs: build-distribution
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: *dist_name
          path: *dist_path
      - name: Install & Upgrade Twine
        run: python -m pip install --upgrade twine
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
